project_id = "vlavfpvrxnmoutybczfy"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.seed-admin]
    verify_jwt = false
  [functions.send-help-message]
    verify_jwt = false
